### ISSUE TITLE
cant find 100,000 or 500,000 ... trades

### ISSUE THREAD

**Issue by dermatzeimnetz** [lukelab04/Stockbot#1]
i update a line of your code to

if '--' not in transaction['ticker'] and ("$50,00" in transaction['amount'] or "$100,00" in transaction['amount'] or "$500,00" in transaction['amount'] or "$5,000,00" in transaction['amount']):

i found out that some major trades have been missing, those with bigger numbers

as example check https://house-stock-watcher-data.s3-us-west-2.amazonaws.com/data/transaction_report_for_12_13_2021.json
to see some of them

it changed the recommandations by a lot

**Comment by lukelab04** [comment]
Thanks, good catch. I've added this in to main.
